CREATE TABLE "page" (
  "fullname" CHARACTER VARYING  PRIMARY KEY,
  "created_at" TIMESTAMP WITH TIME ZONE  NOT NULL,
  "created_by" CHARACTER VARYING  NOT NULL,
  "rating" INTEGER  NOT NULL,
  "title" CHARACTER VARYING  NOT NULL
);

CREATE TABLE "tag" (
  "name" CHARACTER VARYING  NOT NULL,
  "page" CHARACTER VARYING  NOT NULL,
  PRIMARY KEY ("name", "page")
);
